name: Create Release v2

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      # Do the release checkout
      - name: Clone Project
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main

      - name: Get Tag
        id: vars
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "oldtag=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))" >> $GITHUB_ENV

      - name: Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Changelog
        run: |
          echo "## Changes" > CHANGELOG.md
          git log ${{ env.oldtag }}...${{ env.tag }} --pretty=format:"- %h %s" \
            --invert-grep \
            --grep="^chore(CHANGELOG):" \
            --grep="^chore(libs):" \
            --grep="^chore(release):" \
            >> CHANGELOG.md

      # Commit Changelog
      - name: Commit Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore(CHANGELOG): Update changelog for ${{ env.tag }}"

      # Create the TOC release commit on top
      - name: Create TOC Release Commit
        run: |
          git commit --allow-empty -m "chore(release): ${{ env.tag }} release"
          git push origin main

      # Move the tag to include the changelog commit
      - name: Update Tag
        run: |
          git tag -fa ${{ env.tag }} -m "Release ${{ env.tag }}"
          git push origin ${{ env.tag }} --force

      # Make a zip file for GitHub
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: EmoteLDB-${{ env.tag }}.zip
          exclusions: '*.git* *.pkgmeta'

      # Create a release on GitHub
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.tag }}
          name: EmoteLDB
          bodyFile: CHANGELOG.md
          artifacts: EmoteLDB-${{ env.tag }}.zip
          draft: false
          prerelease: false

      # Use the BigWigs packager for Wago output
      - name: Package and Release to Wago
        uses: BigWigsMods/packager@master
        env:
            WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        with:
            args: -g retail -a JZKbwkG1 -n "${{ env.tag }}"
